### ISSUE TITLE
[v1.6.3]Boards Manager Install Support

### ISSUE THREAD

**Issue by per1234** [JChristensen/mighty-1284p#16]
I have already contacted pico-- about this but thought I'd add it here to avoid anyone else duplicating my effort.

I have implemented a working Arduino 1.6.4+ Boards Manager install for Mighty 1284P. The Boards Manager install URL is:
https://per1234.github.io/mighty-1284p/package_JChristensen_mighty-1284p_index.json

I would like to submit a pull request to add this capability to Mighty 1284P. To make this happen two files need to be added somewhere in the repository, the **_package index**_(the .json file in the link above) and the **_installation archive**_. I would need to know where you want these to be put. It's worth giving the location of the package index file some thought because it is best not to change the URL after people have already added it to their preferences. Here are some possible Github locations for these files, you could use a combination of these locations, one for the package index and another for the installation archive:
1. gh-pages branch(e.g., [Adafruit](https://adafruit.github.io/arduino-board-index/package_adafruit_index.json))
   - Pros: URL is shorter(e.g., `https://JChristensen.github.io/mighty-1284p/package_JChristensen_mighty-1284p_index.json` instead of `https://raw.githubusercontent.com/JChristensen/mighty-1284p/v1.6.3/package_JChristensen_mighty-1284p_index.json`).
   - Cons: Adds another branch.
   - I would need you to create the **_gh-pages**_ branch
2. Preexisting branch(e.g., [Sparkfun](https://github.com/sparkfun/Arduino_Boards/tree/master/IDE_Board_Manager))
   - Pros: Doesn't add any more branches to the repository.
   - Cons: Adds files that are useless to someone doing a manual install.
3. Github Releases(e.g., [Sanguino](https://github.com/Lauszus/Sanguino/))
   - Pros: This is already a standard Github way to handle versions.
   - Cons: 
     - The folder structure of the Boards Manager install file is different than the manual installation file(no **_avr**_ folder) so this requires a separate Boards Manager install file to be added to each release. This may be confusing to users trying to figure out which file they need to download for manual installation. You may want to add wording to explain the purpose of the file.
     - Releases can't added or modified via pull request so updates will always be the responsibility of a project collaborator's.
     - The package index file could be added to a release but this is a bit confusing because a single file contains all the versions and you don't want to change the URL with each version.
   - I would need you to create the release.

Note: Using the archive file automatically generated by Github for each commit(e.g., `https://github.com/user-name/project/archive/{commit ID}.zip`) as an installation archive file is not a good idea because Github may later modify the file, making the checksum in the package index file incorrect which will cause a CRC mismatch error during installation in Boards Manager.

If you create the installation archive file then notice that the folder structure is slightly different. All files should be moved up a level from the avr folder and the avr folder should be removed(see https://per1234.github.io/mighty-1284p/mighty-1284p_1.0.0.zip).

![mighty-1284p-boards-manager](https://cloud.githubusercontent.com/assets/8572152/7875826/1d3cc820-0577-11e5-9a88-1901b15a591d.gif)

**Comment by pico--** [comment]
Thanks for your effort on this, Per. As we discussed, I think staying with a manual install method for this repo is preferable given the current state of board manager. A board manager install will overall have more potential downside than upside, and given the current ease of manual installation, it's really a "solution" to a non-problem anyway.
