### ISSUE TITLE
configuring 1284p for 4mhz or 8mhz?

### ISSUE THREAD

**Issue by wilsynet** [JChristensen/mighty-1284p#6]
I'd like to be able to run the 1284p at 4mhz or 8mhz (ideally, 4mhz) so I can run off a lower voltage source for longer periods of time.

Is it as simple as changing AVR_FREQ from 16000000L to 8000000L or 4000000L in the optiboot Makefile?

There used to be a 8mhz bootloader included in the original bootloader directory, but if I understand correctly, that's deprecated now.

**Comment by JChristensen** [comment]
I need to work on bootloaders and get some current and standard options into the repo. 8MHz is commonly used so should of course be represented. I don't often see bootloaders for lower clock speeds, but it has been done. They do have to operate at lower baud rates. If a person is using a 1284P for its larger flash memory, that could make for some lengthy uploads.

With Optiboot v5, various options can be specified on the command line, for instance, to make an 8MHz bootloader operating at 57600 baud upload speed:

```
make atmega1284p AVR_FREQ=8000000 BAUD_RATE=57600
```

In the meantime, until we get them into the repo, I do have 8MHz bootloaders compiled for the 1284P, with upload speeds of 500k, 57.6k, and 28.8k baud. They can be downloaded here:
http://forum.arduino.cc/index.php?topic=245179.msg1755832#msg1755832

An 8MHz entry in the boards.txt file will also be needed (at least one of these also should be added to the repo). You can just start with one of the existing entries and change the f_cpu line to

```
whatever.build.f_cpu=8000000L
```

**Comment by wilsynet** [comment]
Thanks Jack, this is very helpful.  Thank you very much.

Also, upon further consideration, I would probably only find 8MHZ useful (for its lower voltage requirements) and likely not 4MHZ.

**Comment by JChristensen** [comment]
I tend to use 1, 8, or 16MHz. I've experimented with 2 and 4MHz, by setting the clock prescaler (CLKPR register, didn't actually get crystals for those frequencies) but haven't found a need to use them. I have a low-power project that changes its clock on the fly (CLKPR again) between 1MHz and 8MHz. As far as saving power, sleeping the MCU is the biggest bang for the buck if it fits the application.

**Comment by wilsynet** [comment]
Thanks, very useful.

**Comment by JChristensen** [comment]
Hi Wilson, check out the [v1.0.6 branch](https://github.com/JChristensen/mighty-1284p/tree/v1.0.6), it has three 8MHz versions of Optiboot, with upload speeds of 28.8k, 57.6k and 500k.

**Comment by wilsynet** [comment]
Thanks Jack, very much appreciated that you went to the extra trouble to include this in the 1.0.6 branch.

**Comment by JChristensen** [comment]
No problem, hope it will be of some help. Good luck with your 1284P projects!
